import { UserRole } from './permissions';

export interface NavItem {
  title: string;
  href: string;
  icon?: string;
  badge?: string;
  children?: NavItem[];
}

export const navigationConfig: Record<UserRole, NavItem[]> = {
  admin: [
    {
      title: 'Dashboard',
      href: '/dashboard/admin',
      icon: 'LayoutDashboard',
    },
    {
      title: 'User Management',
      href: '/dashboard/admin/users',
      icon: 'Users',
      children: [
        { title: 'All Users', href: '/dashboard/admin/users' },
        { title: 'Students', href: '/dashboard/admin/users/students' },
        { title: 'Mentors', href: '/dashboard/admin/users/mentors' },
        { title: 'Managers', href: '/dashboard/admin/users/managers' },
        { title: 'Admins', href: '/dashboard/admin/users/admins' },
        { title: 'Roles & Permissions', href: '/dashboard/admin/users/roles' },
      ],
    },
    {
      title: 'Course Management',
      href: '/dashboard/admin/courses',
      icon: 'BookOpen',
      children: [
        { title: 'All Courses', href: '/dashboard/admin/courses' },
        { title: 'Add Course', href: '/dashboard/admin/courses/add' },
        { title: 'Categories', href: '/dashboard/admin/courses/categories' },
        { title: 'Course Levels', href: '/dashboard/admin/courses/levels' },
        { title: 'Course Modules', href: '/dashboard/admin/courses/modules' },
        { title: 'Lessons', href: '/dashboard/admin/courses/lessons' },
        { title: 'Videos', href: '/dashboard/admin/courses/videos' },
        { title: 'Assign Mentors', href: '/dashboard/admin/courses/assign-mentors' },
        { title: 'Course Reviews', href: '/dashboard/admin/courses/reviews' },
        { title: 'Certificates', href: '/dashboard/admin/courses/certificates' },
      ],
    },
    {
      title: 'Class Management',
      href: '/dashboard/admin/classes',
      icon: 'Calendar',
      children: [
        { title: 'All Classes', href: '/dashboard/admin/classes' },
        { title: 'Live Classes', href: '/dashboard/admin/classes/live' },
        { title: 'Upcoming Classes', href: '/dashboard/admin/classes/upcoming' },
        { title: 'Recorded Classes', href: '/dashboard/admin/classes/recorded' },
        { title: 'Class Calendar', href: '/dashboard/admin/classes/calendar' },
        { title: 'Attendance', href: '/dashboard/admin/classes/attendance' },
        { title: 'Assign Students', href: '/dashboard/admin/classes/assign-students' },
      ],
    },
    {
      title: 'Student Management',
      href: '/dashboard/admin/students',
      icon: 'GraduationCap',
      children: [
        { title: 'All Students', href: '/dashboard/admin/students' },
        { title: 'Student Progress', href: '/dashboard/admin/students/progress' },
        { title: 'Enrollments', href: '/dashboard/admin/students/enrollments' },
        { title: 'Certificates', href: '/dashboard/admin/students/certificates' },
        { title: 'Attendance', href: '/dashboard/admin/students/attendance' },
        { title: 'Performance Reports', href: '/dashboard/admin/students/performance' },
      ],
    },
    {
      title: 'Mentor Management',
      href: '/dashboard/admin/mentors',
      icon: 'UserCheck',
      children: [
        { title: 'All Mentors', href: '/dashboard/admin/mentors' },
        { title: 'Assign Courses', href: '/dashboard/admin/mentors/assign-courses' },
        { title: 'Assign Classes', href: '/dashboard/admin/mentors/assign-classes' },
        { title: 'Performance', href: '/dashboard/admin/mentors/performance' },
        { title: 'Ratings', href: '/dashboard/admin/mentors/ratings' },
        { title: 'Availability', href: '/dashboard/admin/mentors/availability' },
      ],
    },
    {
      title: 'Blog Management',
      href: '/dashboard/admin/blogs',
      icon: 'FileText',
      children: [
        { title: 'All Blogs', href: '/dashboard/admin/blogs' },
        { title: 'Add Blog', href: '/dashboard/admin/blogs/add' },
        { title: 'Categories', href: '/dashboard/admin/blogs/categories' },
        { title: 'Comments', href: '/dashboard/admin/blogs/comments' },
        { title: 'SEO', href: '/dashboard/admin/blogs/seo' },
      ],
    },
    {
      title: 'Orders & Payments',
      href: '/dashboard/admin/orders',
      icon: 'CreditCard',
      children: [
        { title: 'Orders', href: '/dashboard/admin/orders' },
        { title: 'Payments', href: '/dashboard/admin/payments' },
        { title: 'Transactions', href: '/dashboard/admin/transactions' },
        { title: 'Refunds', href: '/dashboard/admin/refunds' },
        { title: 'Coupons', href: '/dashboard/admin/coupons' },
      ],
    },
    {
      title: 'Reports',
      href: '/dashboard/admin/reports',
      icon: 'BarChart3',
      children: [
        { title: 'Revenue Report', href: '/dashboard/admin/reports/revenue' },
        { title: 'Student Report', href: '/dashboard/admin/reports/students' },
        { title: 'Course Report', href: '/dashboard/admin/reports/courses' },
        { title: 'Mentor Report', href: '/dashboard/admin/reports/mentors' },
        { title: 'Class Report', href: '/dashboard/admin/reports/classes' },
      ],
    },
    {
      title: 'Notifications',
      href: '/dashboard/admin/notifications',
      icon: 'Bell',
      children: [
        { title: 'Email', href: '/dashboard/admin/notifications/email' },
        { title: 'Push Notifications', href: '/dashboard/admin/notifications/push' },
        { title: 'Announcements', href: '/dashboard/admin/notifications/announcements' },
      ],
    },
    {
      title: 'CMS',
      href: '/dashboard/admin/cms',
      icon: 'Globe',
      children: [
        { title: 'Homepage', href: '/dashboard/admin/cms/homepage' },
        { title: 'About', href: '/dashboard/admin/cms/about' },
        { title: 'Contact', href: '/dashboard/admin/cms/contact' },
        { title: 'FAQs', href: '/dashboard/admin/cms/faqs' },
        { title: 'Testimonials', href: '/dashboard/admin/cms/testimonials' },
      ],
    },
    {
      title: 'Settings',
      href: '/dashboard/admin/settings',
      icon: 'Settings',
      children: [
        { title: 'General Settings', href: '/dashboard/admin/settings/general' },
        { title: 'Website Settings', href: '/dashboard/admin/settings/website' },
        { title: 'Email Settings', href: '/dashboard/admin/settings/email' },
        { title: 'Payment Settings', href: '/dashboard/admin/settings/payment' },
        { title: 'API Keys', href: '/dashboard/admin/settings/api' },
        { title: 'Security', href: '/dashboard/admin/settings/security' },
        { title: 'Profile', href: '/dashboard/admin/settings/profile' },
      ],
    },
  ],
  manager: [
    {
      title: 'Dashboard',
      href: '/dashboard/manager',
      icon: 'LayoutDashboard',
    },
    {
      title: 'User Management',
      href: '/dashboard/manager/users',
      icon: 'Users',
      children: [
        { title: 'All Users', href: '/dashboard/manager/users' },
        { title: 'Students', href: '/dashboard/manager/users/students' },
        { title: 'Mentors', href: '/dashboard/manager/users/mentors' },
        { title: 'Managers', href: '/dashboard/manager/users/managers' },
        { title: 'Admins', href: '/dashboard/manager/users/admins' },
        { title: 'Roles & Permissions', href: '/dashboard/manager/users/roles' },
      ],
    },
    {
      title: 'Course Management',
      href: '/dashboard/manager/courses',
      icon: 'BookOpen',
      children: [
        { title: 'All Courses', href: '/dashboard/manager/courses' },
        { title: 'Add Course', href: '/dashboard/manager/courses/add' },
        { title: 'Categories', href: '/dashboard/manager/courses/categories' },
        { title: 'Course Levels', href: '/dashboard/manager/courses/levels' },
        { title: 'Course Modules', href: '/dashboard/manager/courses/modules' },
        { title: 'Lessons', href: '/dashboard/manager/courses/lessons' },
        { title: 'Videos', href: '/dashboard/manager/courses/videos' },
        { title: 'Assign Mentors', href: '/dashboard/manager/courses/assign-mentors' },
        { title: 'Course Reviews', href: '/dashboard/manager/courses/reviews' },
        { title: 'Certificates', href: '/dashboard/manager/courses/certificates' },
      ],
    },
    {
      title: 'Class Management',
      href: '/dashboard/manager/classes',
      icon: 'Calendar',
      children: [
        { title: 'All Classes', href: '/dashboard/manager/classes' },
        { title: 'Live Classes', href: '/dashboard/manager/classes/live' },
        { title: 'Upcoming Classes', href: '/dashboard/manager/classes/upcoming' },
        { title: 'Recorded Classes', href: '/dashboard/manager/classes/recorded' },
        { title: 'Class Calendar', href: '/dashboard/manager/classes/calendar' },
        { title: 'Attendance', href: '/dashboard/manager/classes/attendance' },
        { title: 'Assign Students', href: '/dashboard/manager/classes/assign-students' },
      ],
    },
    {
      title: 'Student Management',
      href: '/dashboard/manager/students',
      icon: 'GraduationCap',
      children: [
        { title: 'All Students', href: '/dashboard/manager/students' },
        { title: 'Student Progress', href: '/dashboard/manager/students/progress' },
        { title: 'Enrollments', href: '/dashboard/manager/students/enrollments' },
        { title: 'Certificates', href: '/dashboard/manager/students/certificates' },
        { title: 'Attendance', href: '/dashboard/manager/students/attendance' },
        { title: 'Performance Reports', href: '/dashboard/manager/students/performance' },
      ],
    },
    {
      title: 'Mentor Management',
      href: '/dashboard/manager/mentors',
      icon: 'UserCheck',
      children: [
        { title: 'All Mentors', href: '/dashboard/manager/mentors' },
        { title: 'Assign Courses', href: '/dashboard/manager/mentors/assign-courses' },
        { title: 'Assign Classes', href: '/dashboard/manager/mentors/assign-classes' },
        { title: 'Performance', href: '/dashboard/manager/mentors/performance' },
        { title: 'Ratings', href: '/dashboard/manager/mentors/ratings' },
        { title: 'Availability', href: '/dashboard/manager/mentors/availability' },
      ],
    },
    {
      title: 'Blog Management',
      href: '/dashboard/manager/blogs',
      icon: 'FileText',
      children: [
        { title: 'All Blogs', href: '/dashboard/manager/blogs' },
        { title: 'Add Blog', href: '/dashboard/manager/blogs/add' },
        { title: 'Categories', href: '/dashboard/manager/blogs/categories' },
        { title: 'Comments', href: '/dashboard/manager/blogs/comments' },
        { title: 'SEO', href: '/dashboard/manager/blogs/seo' },
      ],
    },
    {
      title: 'Orders & Payments',
      href: '/dashboard/manager/orders',
      icon: 'CreditCard',
      children: [
        { title: 'Orders', href: '/dashboard/manager/orders' },
        { title: 'Payments', href: '/dashboard/manager/payments' },
        { title: 'Transactions', href: '/dashboard/manager/transactions' },
        { title: 'Refunds', href: '/dashboard/manager/refunds' },
        { title: 'Coupons', href: '/dashboard/manager/coupons' },
      ],
    },
    {
      title: 'Reports',
      href: '/dashboard/manager/reports',
      icon: 'BarChart3',
      children: [
        { title: 'Revenue Report', href: '/dashboard/manager/reports/revenue' },
        { title: 'Student Report', href: '/dashboard/manager/reports/students' },
        { title: 'Course Report', href: '/dashboard/manager/reports/courses' },
        { title: 'Mentor Report', href: '/dashboard/manager/reports/mentors' },
        { title: 'Class Report', href: '/dashboard/manager/reports/classes' },
      ],
    },
    {
      title: 'Notifications',
      href: '/dashboard/manager/notifications',
      icon: 'Bell',
      children: [
        { title: 'Email', href: '/dashboard/manager/notifications/email' },
        { title: 'Push Notifications', href: '/dashboard/manager/notifications/push' },
        { title: 'Announcements', href: '/dashboard/manager/notifications/announcements' },
      ],
    },
    {
      title: 'CMS',
      href: '/dashboard/manager/cms',
      icon: 'Globe',
      children: [
        { title: 'Homepage', href: '/dashboard/manager/cms/homepage' },
        { title: 'About', href: '/dashboard/manager/cms/about' },
        { title: 'Contact', href: '/dashboard/manager/cms/contact' },
        { title: 'FAQs', href: '/dashboard/manager/cms/faqs' },
        { title: 'Testimonials', href: '/dashboard/manager/cms/testimonials' },
      ],
    },
    {
      title: 'Settings',
      href: '/dashboard/manager/settings',
      icon: 'Settings',
      children: [
        { title: 'General Settings', href: '/dashboard/manager/settings/general' },
        { title: 'Website Settings', href: '/dashboard/manager/settings/website' },
        { title: 'Email Settings', href: '/dashboard/manager/settings/email' },
        { title: 'Payment Settings', href: '/dashboard/manager/settings/payment' },
        { title: 'API Keys', href: '/dashboard/manager/settings/api' },
        { title: 'Security', href: '/dashboard/manager/settings/security' },
        { title: 'Profile', href: '/dashboard/manager/settings/profile' },
      ],
    },
  ],
  mentor: [
    {
      title: 'Dashboard',
      href: '/dashboard/mentor',
      icon: 'LayoutDashboard',
    },
    {
      title: 'My Courses',
      href: '/dashboard/mentor/courses',
      icon: 'BookOpen',
      children: [
        { title: 'All Courses', href: '/dashboard/mentor/courses' },
        { title: 'Course Content', href: '/dashboard/mentor/courses/content' },
        { title: 'Lessons', href: '/dashboard/mentor/courses/lessons' },
        { title: 'Videos', href: '/dashboard/mentor/courses/videos' },
        { title: 'Resources', href: '/dashboard/mentor/courses/resources' },
      ],
    },
    {
      title: 'My Classes',
      href: '/dashboard/mentor/classes',
      icon: 'Calendar',
      children: [
        { title: "Today's Classes", href: '/dashboard/mentor/classes/today' },
        { title: 'Upcoming Classes', href: '/dashboard/mentor/classes/upcoming' },
        { title: 'Live Classes', href: '/dashboard/mentor/classes/live' },
        { title: 'Recorded Classes', href: '/dashboard/mentor/classes/recorded' },
        { title: 'Attendance', href: '/dashboard/mentor/classes/attendance' },
      ],
    },
    {
      title: 'Students',
      href: '/dashboard/mentor/students',
      icon: 'GraduationCap',
      children: [
        { title: 'My Students', href: '/dashboard/mentor/students' },
        { title: 'Student Progress', href: '/dashboard/mentor/students/progress' },
        { title: 'Assignments', href: '/dashboard/mentor/students/assignments' },
        { title: 'Q&A', href: '/dashboard/mentor/students/qa' },
        { title: 'Certificates', href: '/dashboard/mentor/students/certificates' },
      ],
    },
    {
      title: 'Assignments',
      href: '/dashboard/mentor/assignments',
      icon: 'FileCheck',
      children: [
        { title: 'Create Assignment', href: '/dashboard/mentor/assignments/create' },
        { title: 'Review Submission', href: '/dashboard/mentor/assignments/review' },
        { title: 'Grades', href: '/dashboard/mentor/assignments/grades' },
      ],
    },
    {
      title: 'Blog',
      href: '/dashboard/mentor/blogs',
      icon: 'FileText',
      children: [
        { title: 'My Blogs', href: '/dashboard/mentor/blogs' },
        { title: 'Create Blog', href: '/dashboard/mentor/blogs/create' },
        { title: 'Drafts', href: '/dashboard/mentor/blogs/drafts' },
      ],
    },
    {
      title: 'Messages',
      href: '/dashboard/mentor/messages',
      icon: 'MessageSquare',
      children: [
        { title: 'Student Chat', href: '/dashboard/mentor/messages/chat' },
        { title: 'Notifications', href: '/dashboard/mentor/messages/notifications' },
      ],
    },
    {
      title: 'Profile',
      href: '/dashboard/mentor/profile',
      icon: 'User',
      children: [
        { title: 'My Profile', href: '/dashboard/mentor/profile' },
        { title: 'Availability', href: '/dashboard/mentor/profile/availability' },
        { title: 'Change Password', href: '/dashboard/mentor/profile/password' },
      ],
    },
  ],
  student: [
    {
      title: 'Dashboard',
      href: '/dashboard/student',
      icon: 'LayoutDashboard',
    },
    {
      title: 'My Courses',
      href: '/dashboard/student/courses',
      icon: 'BookOpen',
      children: [
        { title: 'Enrolled Courses', href: '/dashboard/student/courses/enrolled' },
        { title: 'Continue Learning', href: '/dashboard/student/courses/continue' },
        { title: 'Wishlist', href: '/dashboard/student/courses/wishlist' },
        { title: 'Completed Courses', href: '/dashboard/student/courses/completed' },
        { title: 'Certificates', href: '/dashboard/student/courses/certificates' },
      ],
    },
    {
      title: 'My Classes',
      href: '/dashboard/student/classes',
      icon: 'Calendar',
      children: [
        { title: 'Upcoming Classes', href: '/dashboard/student/classes/upcoming' },
        { title: 'Live Classes', href: '/dashboard/student/classes/live' },
        { title: 'Recorded Classes', href: '/dashboard/student/classes/recorded' },
        { title: 'Calendar', href: '/dashboard/student/classes/calendar' },
      ],
    },
    {
      title: 'Assignments',
      href: '/dashboard/student/assignments',
      icon: 'FileCheck',
      children: [
        { title: 'My Assignments', href: '/dashboard/student/assignments' },
        { title: 'Submit Assignment', href: '/dashboard/student/assignments/submit' },
        { title: 'Grades', href: '/dashboard/student/assignments/grades' },
      ],
    },
    {
      title: 'Assessments',
      href: '/dashboard/student/assessments',
      icon: 'ClipboardCheck',
      children: [
        { title: 'Quizzes', href: '/dashboard/student/assessments/quizzes' },
        { title: 'Exams', href: '/dashboard/student/assessments/exams' },
        { title: 'Results', href: '/dashboard/student/assessments/results' },
      ],
    },
    {
      title: 'Resources',
      href: '/dashboard/student/resources',
      icon: 'FolderOpen',
      children: [
        { title: 'Downloads', href: '/dashboard/student/resources/downloads' },
        { title: 'Notes', href: '/dashboard/student/resources/notes' },
        { title: 'Study Materials', href: '/dashboard/student/resources/materials' },
      ],
    },
    {
      title: 'Blog',
      href: '/dashboard/student/blogs',
      icon: 'FileText',
      children: [
        { title: 'Blog List', href: '/dashboard/student/blogs' },
        { title: 'Saved Blogs', href: '/dashboard/student/blogs/saved' },
      ],
    },
    {
      title: 'Notifications',
      href: '/dashboard/student/notifications',
      icon: 'Bell',
      children: [
        { title: 'All Notifications', href: '/dashboard/student/notifications' },
        { title: 'Mentor Chat', href: '/dashboard/student/notifications/chat' },
        { title: 'System Messages', href: '/dashboard/student/notifications/system' },
      ],
    },
    {
      title: 'Profile',
      href: '/dashboard/student/profile',
      icon: 'User',
      children: [
        { title: 'My Profile', href: '/dashboard/student/profile' },
        { title: 'Settings', href: '/dashboard/student/profile/settings' },
        { title: 'Change Password', href: '/dashboard/student/profile/password' },
      ],
    },
  ],
};
